// BIO 40A — Question Bank data
// Bone & model images carry a list of named features with normalized (0-1) x,y
// coordinates. A "marker" question shows the image with an arrow at (x,y) and
// asks "What is this structure?" with 4 distractors drawn from same image's
// other features.
//
// Tissue slides are "identify" questions: the whole slide image is the subject,
// and distractors come from a master tissue pool.
//
// Coordinate estimates are FIRST-PASS — use Teacher Mode in the Question Bank
// tab to drag any marker to its correct position. Drag positions persist in
// localStorage and can be exported as JSON.

const BONE_BANK = [
    {
        id: "humerus",
        title: "Humerus",
        image: "bank-images/bones/humerus.jpg",
        features: [
            { id: "head", label: "Head of humerus", x: 0.43, y: 0.14 },
            { id: "anatomical_neck", label: "Anatomical neck", x: 0.44, y: 0.17 },
            { id: "surgical_neck", label: "Surgical neck", x: 0.46, y: 0.21 },
            { id: "greater_tubercle", label: "Greater tubercle", x: 0.38, y: 0.14 },
            { id: "lesser_tubercle", label: "Lesser tubercle", x: 0.41, y: 0.17 },
            { id: "intertubercular_sulcus", label: "Intertubercular sulcus", x: 0.40, y: 0.18 },
            { id: "deltoid_tuberosity", label: "Deltoid tuberosity", x: 0.46, y: 0.40 },
            { id: "body_humerus", label: "Body (shaft) of humerus", x: 0.45, y: 0.55 },
            { id: "medial_epicondyle", label: "Medial epicondyle", x: 0.51, y: 0.86 },
            { id: "lateral_epicondyle", label: "Lateral epicondyle", x: 0.40, y: 0.86 },
            { id: "capitulum", label: "Capitulum", x: 0.43, y: 0.88 },
            { id: "trochlea", label: "Trochlea", x: 0.49, y: 0.88 },
            { id: "olecranon_fossa", label: "Olecranon fossa (posterior)", x: 0.79, y: 0.87 },
            { id: "coronoid_fossa", label: "Coronoid fossa (anterior)", x: 0.46, y: 0.85 },
        ],
    },
    {
        id: "scapula",
        title: "Scapula",
        image: "bank-images/bones/scapula.jpg",
        features: [
            { id: "acromion", label: "Acromion", x: 0.22, y: 0.13 },
            { id: "coracoid_process", label: "Coracoid process", x: 0.17, y: 0.18 },
            { id: "glenoid_cavity", label: "Glenoid cavity", x: 0.25, y: 0.22 },
            { id: "spine_scapula", label: "Spine of scapula", x: 0.28, y: 0.18 },
            { id: "supraspinous_fossa", label: "Supraspinous fossa", x: 0.28, y: 0.13 },
            { id: "infraspinous_fossa", label: "Infraspinous fossa", x: 0.55, y: 0.75 },
            { id: "subscapular_fossa", label: "Subscapular fossa", x: 0.30, y: 0.40 },
            { id: "superior_border", label: "Superior border", x: 0.25, y: 0.10 },
            { id: "medial_border", label: "Medial (vertebral) border", x: 0.40, y: 0.42 },
            { id: "lateral_border", label: "Lateral (axillary) border", x: 0.18, y: 0.55 },
            { id: "superior_angle", label: "Superior angle", x: 0.40, y: 0.15 },
            { id: "inferior_angle", label: "Inferior angle", x: 0.15, y: 0.60 },
            { id: "scapular_notch", label: "Scapular notch", x: 0.21, y: 0.13 },
        ],
    },
    {
        id: "femur",
        title: "Femur",
        image: "bank-images/bones/femur.jpg",
        features: [
            { id: "head_femur", label: "Head of femur", x: 0.42, y: 0.06 },
            { id: "fovea_capitis", label: "Fovea capitis", x: 0.43, y: 0.07 },
            { id: "neck_femur", label: "Neck of femur", x: 0.45, y: 0.10 },
            { id: "greater_trochanter", label: "Greater trochanter", x: 0.39, y: 0.07 },
            { id: "lesser_trochanter", label: "Lesser trochanter", x: 0.49, y: 0.14 },
            { id: "intertrochanteric_line", label: "Intertrochanteric line", x: 0.45, y: 0.13 },
            { id: "intertrochanteric_crest", label: "Intertrochanteric crest", x: 0.79, y: 0.11 },
            { id: "linea_aspera", label: "Linea aspera", x: 0.78, y: 0.45 },
            { id: "gluteal_tuberosity", label: "Gluteal tuberosity", x: 0.77, y: 0.18 },
            { id: "body_femur", label: "Body (shaft) of femur", x: 0.46, y: 0.50 },
            { id: "medial_condyle", label: "Medial condyle", x: 0.50, y: 0.91 },
            { id: "lateral_condyle", label: "Lateral condyle", x: 0.40, y: 0.91 },
            { id: "medial_epicondyle_femur", label: "Medial epicondyle (femur)", x: 0.52, y: 0.89 },
            { id: "lateral_epicondyle_femur", label: "Lateral epicondyle (femur)", x: 0.39, y: 0.89 },
            { id: "intercondylar_fossa", label: "Intercondylar fossa", x: 0.78, y: 0.92 },
            { id: "patellar_surface", label: "Patellar surface", x: 0.45, y: 0.92 },
        ],
    },
    {
        id: "tibia_fibula",
        title: "Tibia & Fibula",
        image: "bank-images/bones/tibia_fibula.jpg",
        features: [
            { id: "tibia", label: "Tibia", x: 0.49, y: 0.45 },
            { id: "fibula", label: "Fibula", x: 0.35, y: 0.45 },
            { id: "medial_condyle_tibia", label: "Medial condyle of tibia", x: 0.52, y: 0.20 },
            { id: "lateral_condyle_tibia", label: "Lateral condyle of tibia", x: 0.42, y: 0.20 },
            { id: "intercondylar_eminence", label: "Intercondylar eminence", x: 0.74, y: 0.18 },
            { id: "tibial_tuberosity", label: "Tibial tuberosity", x: 0.49, y: 0.28 },
            { id: "anterior_crest", label: "Anterior crest/border", x: 0.49, y: 0.50 },
            { id: "medial_malleolus", label: "Medial malleolus", x: 0.55, y: 0.92 },
            { id: "lateral_malleolus", label: "Lateral malleolus", x: 0.34, y: 0.93 },
            { id: "head_fibula", label: "Head of fibula", x: 0.35, y: 0.20 },
            { id: "neck_fibula", label: "Neck of fibula", x: 0.35, y: 0.25 },
        ],
    },
    {
        id: "foot",
        title: "Foot (tarsals & metatarsals)",
        image: "bank-images/bones/foot.jpg",
        features: [
            { id: "calcaneus", label: "Calcaneus", x: 0.62, y: 0.10 },
            { id: "talus", label: "Talus", x: 0.64, y: 0.21 },
            { id: "navicular", label: "Navicular", x: 0.58, y: 0.36 },
            { id: "cuboid", label: "Cuboid", x: 0.50, y: 0.45 },
            { id: "medial_cuneiform", label: "Medial cuneiform", x: 0.65, y: 0.48 },
            { id: "intermediate_cuneiform", label: "Intermediate cuneiform", x: 0.58, y: 0.48 },
            { id: "lateral_cuneiform", label: "Lateral cuneiform", x: 0.52, y: 0.48 },
            { id: "metatarsals", label: "Metatarsals", x: 0.58, y: 0.60 },
            { id: "first_metatarsal", label: "1st metatarsal (big toe side)", x: 0.68, y: 0.62 },
            { id: "fifth_metatarsal", label: "5th metatarsal (little toe side)", x: 0.45, y: 0.62 },
            { id: "proximal_phalanx_foot", label: "Proximal phalanx", x: 0.65, y: 0.80 },
            { id: "distal_phalanx_foot", label: "Distal phalanx", x: 0.65, y: 0.93 },
            { id: "great_toe", label: "Great (big) toe", x: 0.70, y: 0.92 },
        ],
    },
    {
        id: "hand",
        title: "Hand (carpals & metacarpals)",
        image: "bank-images/bones/hand.jpg",
        features: [
            { id: "scaphoid", label: "Scaphoid", x: 0.42, y: 0.12 },
            { id: "lunate", label: "Lunate", x: 0.52, y: 0.10 },
            { id: "triquetrum", label: "Triquetrum", x: 0.60, y: 0.13 },
            { id: "pisiform", label: "Pisiform", x: 0.64, y: 0.16 },
            { id: "trapezium", label: "Trapezium", x: 0.40, y: 0.18 },
            { id: "trapezoid", label: "Trapezoid", x: 0.46, y: 0.20 },
            { id: "capitate", label: "Capitate", x: 0.53, y: 0.20 },
            { id: "hamate", label: "Hamate", x: 0.60, y: 0.20 },
            { id: "metacarpals", label: "Metacarpals", x: 0.52, y: 0.38 },
            { id: "first_metacarpal", label: "1st metacarpal (thumb)", x: 0.36, y: 0.40 },
            { id: "fifth_metacarpal", label: "5th metacarpal (little)", x: 0.68, y: 0.35 },
            { id: "proximal_phalanx_hand", label: "Proximal phalanx", x: 0.52, y: 0.60 },
            { id: "middle_phalanx_hand", label: "Middle phalanx", x: 0.52, y: 0.72 },
            { id: "distal_phalanx_hand", label: "Distal phalanx", x: 0.52, y: 0.85 },
        ],
    },
    {
        id: "radius_ulna",
        title: "Radius & Ulna",
        image: "bank-images/bones/radius_ulna.jpg",
        features: [
            { id: "radius", label: "Radius", x: 0.52, y: 0.50 },
            { id: "ulna", label: "Ulna", x: 0.40, y: 0.50 },
            { id: "head_radius", label: "Head of radius", x: 0.52, y: 0.18 },
            { id: "neck_radius", label: "Neck of radius", x: 0.52, y: 0.22 },
            { id: "radial_tuberosity", label: "Radial tuberosity", x: 0.50, y: 0.28 },
            { id: "styloid_radius", label: "Styloid process of radius", x: 0.55, y: 0.90 },
            { id: "olecranon", label: "Olecranon (of ulna)", x: 0.42, y: 0.12 },
            { id: "coronoid_process", label: "Coronoid process", x: 0.43, y: 0.18 },
            { id: "trochlear_notch", label: "Trochlear notch", x: 0.40, y: 0.16 },
            { id: "radial_notch", label: "Radial notch", x: 0.45, y: 0.18 },
            { id: "ulnar_tuberosity", label: "Ulnar tuberosity", x: 0.42, y: 0.24 },
            { id: "styloid_ulna", label: "Styloid process of ulna", x: 0.38, y: 0.92 },
            { id: "head_ulna", label: "Head of ulna", x: 0.40, y: 0.88 },
            { id: "interosseous_border", label: "Interosseous border", x: 0.47, y: 0.55 },
        ],
    },
    {
        id: "pectoral_girdle",
        title: "Pectoral Girdle (Clavicle)",
        image: "bank-images/bones/pectoral_girdle.jpg",
        features: [
            { id: "clavicle", label: "Clavicle (body)", x: 0.50, y: 0.50 },
            { id: "sternal_end", label: "Sternal end", x: 0.30, y: 0.50 },
            { id: "acromial_end", label: "Acromial end", x: 0.70, y: 0.50 },
        ],
    },
    {
        id: "pelvis_articulated",
        title: "Pelvis (articulated)",
        image: "bank-images/bones/pelvis_articulated.jpg",
        features: [
            { id: "iliac_crest", label: "Iliac crest", x: 0.50, y: 0.18 },
            { id: "asis", label: "Anterior superior iliac spine (ASIS)", x: 0.30, y: 0.40 },
            { id: "psis", label: "Posterior superior iliac spine (PSIS)", x: 0.70, y: 0.30 },
            { id: "pubic_symphysis", label: "Pubic symphysis", x: 0.50, y: 0.80 },
            { id: "acetabulum", label: "Acetabulum", x: 0.30, y: 0.60 },
            { id: "obturator_foramen", label: "Obturator foramen", x: 0.35, y: 0.75 },
            { id: "greater_sciatic_notch", label: "Greater sciatic notch", x: 0.70, y: 0.55 },
            { id: "sacrum_pelvis", label: "Sacrum (within pelvis)", x: 0.50, y: 0.45 },
            { id: "ischial_tuberosity", label: "Ischial tuberosity", x: 0.40, y: 0.85 },
            { id: "iliac_fossa", label: "Iliac fossa", x: 0.40, y: 0.30 },
            { id: "ala_ilium", label: "Ala of ilium", x: 0.25, y: 0.25 },
        ],
    },
    {
        id: "os_coxae",
        title: "Os Coxae (single hip bone)",
        image: "bank-images/bones/os_coxae.jpg",
        features: [
            { id: "ilium", label: "Ilium", x: 0.30, y: 0.30 },
            { id: "ischium", label: "Ischium", x: 0.35, y: 0.70 },
            { id: "pubis", label: "Pubis", x: 0.42, y: 0.62 },
            { id: "iliac_crest_oc", label: "Iliac crest", x: 0.30, y: 0.18 },
            { id: "asis_oc", label: "Anterior superior iliac spine (ASIS)", x: 0.42, y: 0.25 },
            { id: "psis_oc", label: "Posterior superior iliac spine (PSIS)", x: 0.18, y: 0.28 },
            { id: "greater_sciatic_notch_oc", label: "Greater sciatic notch", x: 0.20, y: 0.50 },
            { id: "lesser_sciatic_notch_oc", label: "Lesser sciatic notch", x: 0.22, y: 0.65 },
            { id: "ischial_spine_oc", label: "Ischial spine", x: 0.22, y: 0.60 },
            { id: "ischial_tuberosity_oc", label: "Ischial tuberosity", x: 0.25, y: 0.80 },
            { id: "obturator_foramen_oc", label: "Obturator foramen", x: 0.35, y: 0.65 },
            { id: "acetabulum_oc", label: "Acetabulum", x: 0.35, y: 0.50 },
            { id: "pubic_symphysis_surface", label: "Pubic symphyseal surface", x: 0.45, y: 0.70 },
            { id: "ramus_ischium", label: "Ramus of ischium", x: 0.35, y: 0.75 },
            { id: "auricular_surface_oc", label: "Auricular surface", x: 0.15, y: 0.45 },
        ],
    },
    {
        id: "skull_anterior",
        title: "Skull — Anterior view",
        image: "bank-images/bones/skull_anterior.jpg",
        features: [
            { id: "frontal_bone", label: "Frontal bone", x: 0.50, y: 0.27 },
            { id: "parietal_bone", label: "Parietal bone", x: 0.30, y: 0.20 },
            { id: "temporal_bone_ant", label: "Temporal bone", x: 0.75, y: 0.55 },
            { id: "sphenoid_bone_ant", label: "Sphenoid bone", x: 0.34, y: 0.50 },
            { id: "ethmoid_bone_ant", label: "Ethmoid bone", x: 0.45, y: 0.55 },
            { id: "zygomatic_bone", label: "Zygomatic bone", x: 0.72, y: 0.60 },
            { id: "maxilla", label: "Maxilla", x: 0.50, y: 0.75 },
            { id: "mandible", label: "Mandible", x: 0.50, y: 0.92 },
            { id: "nasal_bone", label: "Nasal bone", x: 0.52, y: 0.50 },
            { id: "lacrimal_bone", label: "Lacrimal bone", x: 0.40, y: 0.55 },
            { id: "vomer", label: "Vomer", x: 0.51, y: 0.72 },
            { id: "inferior_nasal_concha", label: "Inferior nasal concha", x: 0.55, y: 0.65 },
            { id: "orbit", label: "Orbit", x: 0.38, y: 0.55 },
            { id: "supraorbital_margin", label: "Supraorbital margin", x: 0.55, y: 0.48 },
            { id: "supraorbital_foramen", label: "Supraorbital foramen/notch", x: 0.58, y: 0.48 },
            { id: "infraorbital_foramen", label: "Infraorbital foramen", x: 0.55, y: 0.63 },
            { id: "mental_foramen", label: "Mental foramen", x: 0.55, y: 0.90 },
            { id: "mental_protuberance", label: "Mental protuberance", x: 0.50, y: 0.95 },
            { id: "frontal_squama", label: "Frontal squama", x: 0.50, y: 0.33 },
            { id: "sagittal_suture_ant", label: "Sagittal suture", x: 0.55, y: 0.13 },
            { id: "inferior_orbital_fissure", label: "Inferior orbital fissure", x: 0.65, y: 0.65 },
        ],
    },
    {
        id: "skull_lateral",
        title: "Skull — Lateral view",
        image: "bank-images/bones/skull_lateral.jpg",
        features: [
            { id: "frontal_lateral", label: "Frontal bone", x: 0.65, y: 0.30 },
            { id: "parietal_lateral", label: "Parietal bone", x: 0.45, y: 0.25 },
            { id: "temporal_lateral", label: "Temporal bone", x: 0.45, y: 0.55 },
            { id: "occipital_lateral", label: "Occipital bone", x: 0.20, y: 0.50 },
            { id: "sphenoid_lateral", label: "Sphenoid bone", x: 0.62, y: 0.55 },
            { id: "zygomatic_lateral", label: "Zygomatic bone", x: 0.78, y: 0.65 },
            { id: "zygomatic_arch", label: "Zygomatic arch", x: 0.55, y: 0.65 },
            { id: "maxilla_lateral", label: "Maxilla", x: 0.78, y: 0.75 },
            { id: "mandible_lateral", label: "Mandible (body)", x: 0.70, y: 0.85 },
            { id: "mandibular_condyle", label: "Mandibular condyle", x: 0.50, y: 0.65 },
            { id: "mental_protuberance_l", label: "Mental protuberance", x: 0.85, y: 0.85 },
            { id: "mastoid_process", label: "Mastoid process", x: 0.40, y: 0.72 },
            { id: "styloid_process", label: "Styloid process", x: 0.45, y: 0.73 },
            { id: "external_acoustic_meatus", label: "External acoustic meatus", x: 0.42, y: 0.65 },
            { id: "coronal_suture", label: "Coronal suture", x: 0.58, y: 0.20 },
            { id: "squamous_suture", label: "Squamous suture", x: 0.45, y: 0.40 },
            { id: "lambdoid_suture", label: "Lambdoid suture", x: 0.27, y: 0.40 },
            { id: "external_occipital_protuberance", label: "External occipital protuberance", x: 0.20, y: 0.65 },
            { id: "lacrimal_fossa", label: "Lacrimal fossa", x: 0.85, y: 0.55 },
            { id: "nasal_bone_lateral", label: "Nasal bone", x: 0.85, y: 0.62 },
        ],
    },
    {
        id: "skull_posterior_superior",
        title: "Skull — Posterior / Superior view",
        image: "bank-images/bones/skull_posterior_superior.jpg",
        features: [
            { id: "parietal_post", label: "Parietal bone", x: 0.50, y: 0.30 },
            { id: "occipital_post", label: "Occipital bone", x: 0.50, y: 0.65 },
            { id: "sagittal_suture_post", label: "Sagittal suture", x: 0.50, y: 0.25 },
            { id: "lambdoid_suture_post", label: "Lambdoid suture", x: 0.50, y: 0.55 },
            { id: "external_occipital_protuberance_post", label: "External occipital protuberance", x: 0.50, y: 0.78 },
            { id: "frontal_bone_sup", label: "Frontal bone (superior aspect)", x: 0.50, y: 0.12 },
            { id: "coronal_suture_sup", label: "Coronal suture (superior view)", x: 0.50, y: 0.20 },
        ],
    },
    {
        id: "skull_inferior",
        title: "Skull — Inferior view",
        image: "bank-images/bones/skull_inferior.jpg",
        features: [
            { id: "occipital_condyle", label: "Occipital condyle", x: 0.50, y: 0.40 },
            { id: "foramen_magnum", label: "Foramen magnum", x: 0.50, y: 0.42 },
            { id: "mastoid_process_inf", label: "Mastoid process", x: 0.35, y: 0.50 },
            { id: "styloid_process_inf", label: "Styloid process", x: 0.40, y: 0.48 },
            { id: "hard_palate", label: "Hard palate", x: 0.50, y: 0.75 },
            { id: "palatine_process_maxilla", label: "Palatine process of maxilla", x: 0.50, y: 0.70 },
            { id: "vomer_inf", label: "Vomer", x: 0.50, y: 0.60 },
            { id: "mandibular_fossa", label: "Mandibular fossa", x: 0.40, y: 0.55 },
            { id: "zygomatic_arch_inf", label: "Zygomatic arch", x: 0.30, y: 0.62 },
            { id: "external_occipital_protuberance_inf", label: "External occipital protuberance", x: 0.50, y: 0.15 },
            { id: "maxilla_inf", label: "Maxilla", x: 0.50, y: 0.80 },
            { id: "incisive_foramen", label: "Incisive foramen", x: 0.50, y: 0.82 },
            { id: "foramen_ovale", label: "Foramen ovale", x: 0.43, y: 0.50 },
            { id: "foramen_spinosum", label: "Foramen spinosum", x: 0.42, y: 0.48 },
        ],
    },
    {
        id: "skull_floor",
        title: "Skull — Cranial floor (interior)",
        image: "bank-images/bones/skull_floor.jpg",
        features: [
            { id: "crista_galli", label: "Crista galli", x: 0.50, y: 0.20 },
            { id: "cribriform_plate", label: "Cribriform plate (ethmoid)", x: 0.50, y: 0.22 },
            { id: "sella_turcica", label: "Sella turcica", x: 0.50, y: 0.40 },
            { id: "foramen_magnum_floor", label: "Foramen magnum", x: 0.50, y: 0.85 },
            { id: "petrous_part_temporal", label: "Petrous part of temporal bone", x: 0.35, y: 0.55 },
            { id: "greater_wing_sphenoid", label: "Greater wing of sphenoid", x: 0.35, y: 0.32 },
            { id: "lesser_wing_sphenoid", label: "Lesser wing of sphenoid", x: 0.40, y: 0.28 },
            { id: "optic_canal", label: "Optic canal", x: 0.45, y: 0.32 },
            { id: "foramen_ovale_floor", label: "Foramen ovale", x: 0.40, y: 0.42 },
            { id: "foramen_rotundum", label: "Foramen rotundum", x: 0.42, y: 0.36 },
            { id: "foramen_spinosum_floor", label: "Foramen spinosum", x: 0.38, y: 0.45 },
            { id: "jugular_foramen", label: "Jugular foramen", x: 0.35, y: 0.65 },
            { id: "internal_acoustic_meatus", label: "Internal acoustic meatus", x: 0.40, y: 0.60 },
        ],
    },
    {
        id: "disarticulated_cranial",
        title: "Disarticulated cranial bones",
        image: "bank-images/bones/disarticulated_cranial.jpg",
        features: [
            { id: "frontal_disart", label: "Frontal bone", x: 0.20, y: 0.30 },
            { id: "parietal_disart", label: "Parietal bone", x: 0.40, y: 0.30 },
            { id: "occipital_disart", label: "Occipital bone", x: 0.60, y: 0.30 },
            { id: "temporal_disart", label: "Temporal bone", x: 0.80, y: 0.30 },
            { id: "sphenoid_disart", label: "Sphenoid bone", x: 0.30, y: 0.65 },
            { id: "ethmoid_disart", label: "Ethmoid bone", x: 0.55, y: 0.65 },
        ],
    },
    {
        id: "face_orbit",
        title: "Face & Orbit",
        image: "bank-images/bones/face_orbit.jpg",
        features: [
            { id: "frontal_orbit", label: "Frontal bone (orbit roof)", x: 0.50, y: 0.20 },
            { id: "nasal_orbit", label: "Nasal bone", x: 0.30, y: 0.40 },
            { id: "lacrimal_orbit", label: "Lacrimal bone", x: 0.42, y: 0.45 },
            { id: "ethmoid_orbit", label: "Ethmoid bone", x: 0.50, y: 0.55 },
            { id: "sphenoid_orbit", label: "Sphenoid bone (orbit)", x: 0.65, y: 0.55 },
            { id: "zygomatic_orbit", label: "Zygomatic bone (orbit)", x: 0.75, y: 0.65 },
            { id: "maxilla_orbit", label: "Maxilla", x: 0.55, y: 0.80 },
            { id: "inferior_orbital_fissure_fo", label: "Inferior orbital fissure", x: 0.55, y: 0.70 },
            { id: "superior_orbital_fissure", label: "Superior orbital fissure", x: 0.55, y: 0.45 },
            { id: "optic_canal_fo", label: "Optic canal", x: 0.48, y: 0.50 },
            { id: "supraorbital_foramen_fo", label: "Supraorbital foramen", x: 0.52, y: 0.30 },
            { id: "infraorbital_foramen_fo", label: "Infraorbital foramen", x: 0.55, y: 0.85 },
        ],
    },
    {
        id: "cervical_vertebrae",
        title: "Cervical Vertebrae (Atlas, Axis, typical)",
        image: "bank-images/bones/cervical_vertebrae.jpg",
        features: [
            { id: "atlas", label: "Atlas (C1)", x: 0.25, y: 0.35 },
            { id: "axis", label: "Axis (C2)", x: 0.50, y: 0.35 },
            { id: "typical_cervical", label: "Typical cervical vertebra (C3–C7)", x: 0.75, y: 0.35 },
            { id: "dens", label: "Dens (odontoid process of axis)", x: 0.50, y: 0.25 },
            { id: "transverse_foramen", label: "Transverse foramen", x: 0.75, y: 0.40 },
            { id: "bifid_spinous_process", label: "Bifid spinous process", x: 0.75, y: 0.55 },
            { id: "vertebral_foramen_cerv", label: "Vertebral foramen", x: 0.75, y: 0.45 },
            { id: "anterior_arch_atlas", label: "Anterior arch of atlas", x: 0.25, y: 0.30 },
            { id: "posterior_arch_atlas", label: "Posterior arch of atlas", x: 0.25, y: 0.50 },
        ],
    },
    {
        id: "lumbar_vertebra",
        title: "Lumbar Vertebra",
        image: "bank-images/bones/lumbar_vertebra.jpg",
        features: [
            { id: "body_lumbar", label: "Body (centrum)", x: 0.62, y: 0.40 },
            { id: "spinous_process_lumbar", label: "Spinous process", x: 0.55, y: 0.15 },
            { id: "transverse_process_lumbar", label: "Transverse process", x: 0.45, y: 0.27 },
            { id: "lamina_lumbar", label: "Lamina", x: 0.50, y: 0.22 },
            { id: "pedicle_lumbar", label: "Pedicle", x: 0.55, y: 0.30 },
            { id: "vertebral_foramen_lumbar", label: "Vertebral foramen", x: 0.55, y: 0.32 },
            { id: "superior_articular_process_lumbar", label: "Superior articular process", x: 0.60, y: 0.20 },
            { id: "inferior_articular_process_lumbar", label: "Inferior articular process", x: 0.55, y: 0.40 },
            { id: "superior_vertebral_notch", label: "Superior vertebral notch", x: 0.65, y: 0.75 },
        ],
    },
    {
        id: "thoracic_column",
        title: "Thoracic Column",
        image: "bank-images/bones/thoracic_column.jpg",
        features: [
            { id: "body_thoracic", label: "Body of thoracic vertebra", x: 0.50, y: 0.50 },
            { id: "spinous_process_thoracic", label: "Spinous process (long, pointing down)", x: 0.30, y: 0.50 },
            { id: "transverse_process_thoracic", label: "Transverse process", x: 0.50, y: 0.40 },
            { id: "superior_costal_facet", label: "Superior costal facet (rib articulation)", x: 0.55, y: 0.45 },
            { id: "inferior_costal_facet", label: "Inferior costal facet", x: 0.55, y: 0.55 },
            { id: "transverse_costal_facet", label: "Transverse costal facet", x: 0.50, y: 0.45 },
            { id: "intervertebral_disc_space", label: "Intervertebral disc space", x: 0.50, y: 0.60 },
        ],
    },
    {
        id: "sacrum_coccyx",
        title: "Sacrum & Coccyx",
        image: "bank-images/bones/sacrum_coccyx.jpg",
        features: [
            { id: "sacrum_body", label: "Sacrum", x: 0.28, y: 0.40 },
            { id: "coccyx", label: "Coccyx", x: 0.28, y: 0.65 },
            { id: "sacral_ala", label: "Sacral ala", x: 0.15, y: 0.15 },
            { id: "base_sacrum", label: "Base of sacrum", x: 0.18, y: 0.20 },
            { id: "sacral_promontory", label: "Sacral promontory", x: 0.20, y: 0.23 },
            { id: "sacral_foramina_ant", label: "Anterior sacral foramina", x: 0.30, y: 0.40 },
            { id: "transverse_line", label: "Transverse line (ridge)", x: 0.30, y: 0.40 },
            { id: "apex_sacrum", label: "Apex of sacrum", x: 0.25, y: 0.60 },
            { id: "superior_articular_process_sacrum", label: "Superior articular process", x: 0.35, y: 0.15 },
            { id: "median_sacral_crest", label: "Median sacral crest", x: 0.65, y: 0.70 },
            { id: "lateral_sacral_crest", label: "Lateral sacral crest", x: 0.75, y: 0.65 },
            { id: "intermediate_sacral_crest", label: "Intermediate sacral crest", x: 0.70, y: 0.70 },
            { id: "sacral_foramina_post", label: "Posterior sacral foramina", x: 0.65, y: 0.75 },
            { id: "auricular_surface_sacrum", label: "Auricular surface", x: 0.78, y: 0.60 },
            { id: "sacral_tuberosity", label: "Sacral tuberosity", x: 0.80, y: 0.65 },
            { id: "sacral_cornu", label: "Sacral cornu", x: 0.65, y: 0.83 },
            { id: "sacral_hiatus", label: "Sacral hiatus", x: 0.65, y: 0.83 },
        ],
    },
    {
        id: "sternum_ribs",
        title: "Sternum & Ribs",
        image: "bank-images/bones/sternum_ribs.jpg",
        features: [
            { id: "manubrium", label: "Manubrium", x: 0.55, y: 0.25 },
            { id: "body_sternum", label: "Body of sternum", x: 0.55, y: 0.45 },
            { id: "xiphoid_process", label: "Xiphoid process", x: 0.55, y: 0.62 },
            { id: "sternal_angle", label: "Sternal angle", x: 0.60, y: 0.32 },
            { id: "jugular_notch", label: "Jugular (suprasternal) notch", x: 0.55, y: 0.20 },
            { id: "true_ribs", label: "True ribs (1–7)", x: 0.85, y: 0.40 },
            { id: "false_ribs", label: "False ribs (8–10)", x: 0.85, y: 0.65 },
            { id: "floating_ribs", label: "Floating ribs (11–12)", x: 0.50, y: 0.80 },
            { id: "costal_cartilage", label: "Costal (hyaline) cartilage", x: 0.78, y: 0.55 },
            { id: "intercostal_space", label: "Intercostal space", x: 0.85, y: 0.60 },
            { id: "clavicle_sr", label: "Clavicle", x: 0.78, y: 0.18 },
            { id: "scapula_sr", label: "Scapula", x: 0.92, y: 0.25 },
        ],
    },
    {
        id: "hyoid_ossicles",
        title: "Hyoid & Auditory Ossicles",
        image: "bank-images/bones/hyoid_ossicles.jpg",
        features: [
            { id: "hyoid_bone", label: "Hyoid bone", x: 0.30, y: 0.50 },
            { id: "malleus", label: "Malleus", x: 0.55, y: 0.45 },
            { id: "incus", label: "Incus", x: 0.70, y: 0.45 },
            { id: "stapes", label: "Stapes", x: 0.85, y: 0.45 },
            { id: "greater_horn_hyoid", label: "Greater horn (of hyoid)", x: 0.38, y: 0.45 },
            { id: "lesser_horn_hyoid", label: "Lesser horn (of hyoid)", x: 0.30, y: 0.42 },
            { id: "body_hyoid", label: "Body of hyoid", x: 0.25, y: 0.55 },
        ],
    },
];

const MODEL_BANK = [
    {
        id: "cell_model",
        title: "Cell Model (animal cell)",
        image: "bank-images/models/cell_model.jpeg",
        features: [
            { id: "nucleus", label: "Nucleus", x: 0.50, y: 0.50 },
            { id: "nucleolus", label: "Nucleolus", x: 0.50, y: 0.50 },
            { id: "nuclear_envelope", label: "Nuclear envelope", x: 0.48, y: 0.45 },
            { id: "mitochondria", label: "Mitochondria", x: 0.35, y: 0.40 },
            { id: "rough_er", label: "Rough endoplasmic reticulum", x: 0.55, y: 0.55 },
            { id: "smooth_er", label: "Smooth endoplasmic reticulum", x: 0.30, y: 0.55 },
            { id: "golgi", label: "Golgi apparatus", x: 0.40, y: 0.65 },
            { id: "ribosome", label: "Ribosome", x: 0.55, y: 0.50 },
            { id: "centrioles", label: "Centrioles", x: 0.60, y: 0.40 },
            { id: "lysosome", label: "Lysosome", x: 0.65, y: 0.55 },
            { id: "plasma_membrane", label: "Plasma membrane", x: 0.50, y: 0.10 },
            { id: "cytoplasm", label: "Cytoplasm", x: 0.20, y: 0.30 },
            { id: "vesicle", label: "Vesicle", x: 0.70, y: 0.65 },
            { id: "peroxisome", label: "Peroxisome", x: 0.30, y: 0.70 },
        ],
    },
    {
        id: "skin_model",
        title: "Skin Model",
        image: "bank-images/models/skin_model.jpeg",
        features: [
            { id: "epidermis", label: "Epidermis", x: 0.50, y: 0.10 },
            { id: "dermis", label: "Dermis", x: 0.50, y: 0.40 },
            { id: "hypodermis", label: "Hypodermis (subcutaneous)", x: 0.50, y: 0.80 },
            { id: "papillary_layer", label: "Papillary layer of dermis", x: 0.50, y: 0.25 },
            { id: "reticular_layer", label: "Reticular layer of dermis", x: 0.50, y: 0.55 },
            { id: "hair_follicle", label: "Hair follicle", x: 0.55, y: 0.50 },
            { id: "hair_shaft", label: "Hair shaft", x: 0.55, y: 0.15 },
            { id: "sebaceous_gland", label: "Sebaceous gland", x: 0.45, y: 0.40 },
            { id: "sudoriferous_gland", label: "Sudoriferous (sweat) gland", x: 0.40, y: 0.70 },
            { id: "arrector_pili", label: "Arrector pili muscle", x: 0.50, y: 0.40 },
            { id: "meissner_corpuscle", label: "Meissner corpuscle", x: 0.30, y: 0.25 },
            { id: "pacinian_corpuscle", label: "Pacinian corpuscle", x: 0.30, y: 0.75 },
            { id: "stratum_corneum", label: "Stratum corneum", x: 0.50, y: 0.05 },
            { id: "stratum_basale", label: "Stratum basale", x: 0.50, y: 0.18 },
        ],
    },
    {
        id: "skin_diagram",
        title: "Skin Diagram (illustration)",
        image: "bank-images/models/skin_diagram.jpeg",
        features: [
            { id: "epidermis_d", label: "Epidermis", x: 0.50, y: 0.10 },
            { id: "dermis_d", label: "Dermis", x: 0.50, y: 0.40 },
            { id: "hypodermis_d", label: "Hypodermis", x: 0.50, y: 0.85 },
            { id: "hair_follicle_d", label: "Hair follicle", x: 0.55, y: 0.50 },
            { id: "sebaceous_gland_d", label: "Sebaceous gland", x: 0.45, y: 0.40 },
            { id: "sweat_gland_d", label: "Sweat gland", x: 0.40, y: 0.75 },
            { id: "arrector_pili_d", label: "Arrector pili", x: 0.55, y: 0.45 },
        ],
    },
    {
        id: "mitosis_stages",
        title: "Mitosis Stages",
        image: "bank-images/models/mitosis_stages.jpeg",
        features: [
            { id: "interphase", label: "Interphase", x: 0.10, y: 0.50 },
            { id: "prophase", label: "Prophase", x: 0.28, y: 0.50 },
            { id: "metaphase", label: "Metaphase", x: 0.48, y: 0.50 },
            { id: "anaphase", label: "Anaphase", x: 0.68, y: 0.50 },
            { id: "telophase", label: "Telophase", x: 0.88, y: 0.50 },
        ],
    },
];

// 12 station photos from the practice exam — re-use as marker-style questions
// with new highlights on different anatomy.
const STATION_REUSE_BANK = [
    {
        id: "station_femur_photo",
        title: "Lab Femur (close-up photo)",
        image: "images/station-10.jpg",
        features: [
            { id: "p_greater_trochanter", label: "Greater trochanter", x: 0.55, y: 0.20 },
            { id: "p_lesser_trochanter", label: "Lesser trochanter", x: 0.62, y: 0.25 },
            { id: "p_head_femur", label: "Head of femur", x: 0.50, y: 0.18 },
            { id: "p_body_femur", label: "Body of femur", x: 0.55, y: 0.50 },
            { id: "p_lateral_condyle", label: "Lateral condyle", x: 0.45, y: 0.85 },
            { id: "p_medial_condyle", label: "Medial condyle", x: 0.55, y: 0.85 },
        ],
    },
    {
        id: "station_humerus_photo",
        title: "Lab Humerus (close-up photo)",
        image: "images/station-08.jpg",
        features: [
            { id: "p_h_head", label: "Head of humerus", x: 0.50, y: 0.20 },
            { id: "p_h_greater_tubercle", label: "Greater tubercle", x: 0.48, y: 0.18 },
            { id: "p_h_lesser_tubercle", label: "Lesser tubercle", x: 0.52, y: 0.20 },
            { id: "p_h_trochlea", label: "Trochlea", x: 0.55, y: 0.80 },
            { id: "p_h_capitulum", label: "Capitulum", x: 0.50, y: 0.80 },
        ],
    },
    {
        id: "station_skull_photo",
        title: "Lab Skull (close-up photo)",
        image: "images/station-04.jpg",
        features: [
            { id: "p_s_coronal", label: "Coronal suture", x: 0.45, y: 0.40 },
            { id: "p_s_sagittal", label: "Sagittal suture", x: 0.50, y: 0.30 },
            { id: "p_s_squamous", label: "Squamous suture", x: 0.40, y: 0.55 },
            { id: "p_s_lambdoid", label: "Lambdoid suture", x: 0.30, y: 0.45 },
            { id: "p_s_mastoid", label: "Mastoid process", x: 0.40, y: 0.70 },
            { id: "p_s_styloid", label: "Styloid process", x: 0.45, y: 0.72 },
            { id: "p_s_zygomatic_process", label: "Zygomatic process", x: 0.55, y: 0.65 },
            { id: "p_s_supraorbital", label: "Supraorbital foramen/notch", x: 0.60, y: 0.50 },
        ],
    },
    {
        id: "station_vertebra_photo",
        title: "Lab Vertebrae (close-up photo)",
        image: "images/station-05.jpg",
        features: [
            { id: "p_v_dens", label: "Dens (of axis)", x: 0.40, y: 0.30 },
            { id: "p_v_spinous", label: "Spinous process", x: 0.55, y: 0.60 },
            { id: "p_v_transverse", label: "Transverse process", x: 0.50, y: 0.45 },
            { id: "p_v_lamina", label: "Lamina", x: 0.55, y: 0.40 },
            { id: "p_v_pedicle", label: "Pedicle", x: 0.50, y: 0.40 },
        ],
    },
    {
        id: "station_pelvis_photo",
        title: "Lab Pelvis (close-up photo)",
        image: "images/station-09.jpg",
        features: [
            { id: "p_p_pubic_symphysis", label: "Pubic symphysis", x: 0.45, y: 0.60 },
            { id: "p_p_iliac_crest", label: "Iliac crest", x: 0.45, y: 0.20 },
            { id: "p_p_greater_sciatic_notch", label: "Greater sciatic notch", x: 0.50, y: 0.40 },
            { id: "p_p_obturator_foramen", label: "Obturator foramen", x: 0.55, y: 0.65 },
            { id: "p_p_sacral_hiatus", label: "Sacral hiatus", x: 0.40, y: 0.70 },
        ],
    },
    {
        id: "station_mandible_photo",
        title: "Lab Mandible (close-up photo)",
        image: "images/station-07.jpg",
        features: [
            { id: "p_m_mental_protuberance", label: "Mental protuberance", x: 0.55, y: 0.50 },
            { id: "p_m_mental_foramen", label: "Mental foramen", x: 0.50, y: 0.45 },
            { id: "p_m_alveolar_process", label: "Alveolar process", x: 0.55, y: 0.40 },
            { id: "p_m_mandibular_condyle", label: "Mandibular condyle", x: 0.35, y: 0.35 },
        ],
    },
    {
        id: "station_handfoot_photo",
        title: "Lab Hand & Foot (close-up photo)",
        image: "images/station-11.jpg",
        features: [
            { id: "p_hf_scaphoid", label: "Scaphoid", x: 0.35, y: 0.55 },
            { id: "p_hf_lunate", label: "Lunate", x: 0.40, y: 0.55 },
            { id: "p_hf_capitate", label: "Capitate", x: 0.42, y: 0.60 },
            { id: "p_hf_calcaneus", label: "Calcaneus", x: 0.55, y: 0.25 },
            { id: "p_hf_talus", label: "Talus", x: 0.55, y: 0.35 },
            { id: "p_hf_navicular", label: "Navicular", x: 0.55, y: 0.42 },
        ],
    },
];

// Master tissue identification bank (28 slides). The whole slide IS the answer;
// distractors are sampled from the global tissue pool.
const TISSUE_BANK = [
    { id: "compact_bone_ground", label: "Compact bone (ground section)", image: "bank-images/tissues/compact_bone_ground.png", category: "bone" },
    { id: "compact_spongy_bone", label: "Compact + spongy bone", image: "bank-images/tissues/compact_spongy_bone.png", category: "bone" },
    { id: "hyaline_cartilage_trachea", label: "Hyaline cartilage (trachea)", image: "bank-images/tissues/hyaline_cartilage_trachea.png", category: "cartilage" },
    { id: "elastic_cartilage_ear", label: "Elastic cartilage (ear)", image: "bank-images/tissues/elastic_cartilage_ear.png", category: "cartilage" },
    { id: "fibrocartilage_disc", label: "Fibrocartilage (intervertebral disc)", image: "bank-images/tissues/fibrocartilage_disc.png", category: "cartilage" },
    { id: "blood_smear", label: "Blood smear", image: "bank-images/tissues/blood_smear.png", category: "blood" },
    { id: "areolar_mesentery", label: "Areolar connective tissue (mesentery)", image: "bank-images/tissues/areolar_mesentery.png", category: "connective" },
    { id: "adipose_white", label: "Adipose tissue (white)", image: "bank-images/tissues/adipose_white.png", category: "connective" },
    { id: "adipose_brown", label: "Adipose tissue (brown)", image: "bank-images/tissues/adipose_brown.png", category: "connective" },
    { id: "dense_irregular_dermis", label: "Dense irregular connective tissue (dermis)", image: "bank-images/tissues/dense_irregular_dermis.png", category: "connective" },
    { id: "dense_regular_tendon", label: "Dense regular connective tissue (tendon)", image: "bank-images/tissues/dense_regular_tendon.png", category: "connective" },
    { id: "reticular_spleen", label: "Reticular connective tissue (spleen)", image: "bank-images/tissues/reticular_spleen.png", category: "connective" },
    { id: "mucous_ct_umbilical", label: "Mucous connective tissue (umbilical cord)", image: "bank-images/tissues/mucous_ct_umbilical.png", category: "connective" },
    { id: "mast_cells_toluidine", label: "Mast cells (toluidine blue)", image: "bank-images/tissues/mast_cells_toluidine.png", category: "connective" },
    { id: "simple_squamous_pavement", label: "Simple squamous epithelium", image: "bank-images/tissues/simple_squamous_pavement.png", category: "epithelium" },
    { id: "simple_cuboidal_pancreas", label: "Simple cuboidal epithelium (pancreas)", image: "bank-images/tissues/simple_cuboidal_pancreas.png", category: "epithelium" },
    { id: "simple_columnar_jejunum", label: "Simple columnar epithelium (jejunum)", image: "bank-images/tissues/simple_columnar_jejunum.png", category: "epithelium" },
    { id: "pseudostratified_trachea", label: "Pseudostratified ciliated columnar epithelium (trachea)", image: "bank-images/tissues/pseudostratified_trachea.png", category: "epithelium" },
    { id: "strat_squamous_keratinized", label: "Stratified squamous epithelium (keratinized)", image: "bank-images/tissues/strat_squamous_keratinized.png", category: "epithelium" },
    { id: "strat_squamous_nonkeratinized", label: "Stratified squamous epithelium (non-keratinized)", image: "bank-images/tissues/strat_squamous_nonkeratinized.png", category: "epithelium" },
    { id: "strat_cuboidal_esophagus", label: "Stratified cuboidal epithelium", image: "bank-images/tissues/strat_cuboidal_esophagus.png", category: "epithelium" },
    { id: "transitional_bladder", label: "Transitional epithelium (bladder)", image: "bank-images/tissues/transitional_bladder.png", category: "epithelium" },
    { id: "cardiac_intercalated", label: "Cardiac muscle (intercalated discs)", image: "bank-images/tissues/cardiac_intercalated.png", category: "muscle" },
    { id: "skeletal_long", label: "Skeletal muscle (longitudinal)", image: "bank-images/tissues/skeletal_long.png", category: "muscle" },
    { id: "smooth_muscle", label: "Smooth muscle", image: "bank-images/tissues/smooth_muscle.png", category: "muscle" },
    { id: "neuron_golgi", label: "Neuron (Golgi stain)", image: "bank-images/tissues/neuron_golgi.png", category: "nervous" },
    { id: "peripheral_nerve", label: "Peripheral nerve (cross-section)", image: "bank-images/tissues/peripheral_nerve.png", category: "nervous" },
    { id: "dorsal_root_ganglion", label: "Dorsal root ganglion", image: "bank-images/tissues/dorsal_root_ganglion.png", category: "nervous" },
];

// Build a flat list of every marker question and every tissue question.
function buildQuestionPool() {
    const pool = [];

    const markerSets = [BONE_BANK, MODEL_BANK, STATION_REUSE_BANK];
    markerSets.forEach((bank) => {
        bank.forEach((item) => {
            item.features.forEach((feat) => {
                pool.push({
                    type: "marker",
                    questionId: `${item.id}__${feat.id}`,
                    imageId: item.id,
                    title: item.title,
                    image: item.image,
                    feature: feat,
                    allFeatures: item.features,
                });
            });
        });
    });

    TISSUE_BANK.forEach((t) => {
        pool.push({
            type: "identify",
            questionId: `tissue__${t.id}`,
            title: "Tissue Slide",
            image: t.image,
            answerLabel: t.label,
            category: t.category,
            allTissues: TISSUE_BANK,
        });
    });

    return pool;
}

const QUESTION_POOL = buildQuestionPool();
